---
- name: Create wordpress and mysql containers using docker and ansible
  hosts: all
  tasks:
    - name: Create a mysql container
      docker_container:
        name: mydb
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: intelliqit

    - name: Create a nginx container
      docker_container:
        name: mynginx
        image: nginx
        ports:
          - 8888:80
...
