---
- name: Configure apache2
  hosts: all
  serial: 1
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Edit the index.html file
      copy:
        content: "Intelliq"
        dest: /var/www/html/index.html
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: Check apache response on server1
      uri:
        url: http://10.10.11.56
        status_code: 200
    - name: Check apache response on server2
      uri:
        url: http://10.10.11.57
        status_code: 200
...







