---
- name: Install git based on OS flavour
  hosts: all
  tasks:
    - name: Install git on Ubuntu servers using apt 
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install git on RHEL servers using yum
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
