---
- name: Configuring tomcat using loops
  hosts: all
  tasks:
    - name: Install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: Copy tocmat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 1 minute
      pause:
        minutes: 1
    - name: Check tomcat response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.46.76:9090
        - http://172.31.32.134:9090
...







