---
- name: Check if f1 folder is present if not create a file f1
  hosts: all
  tasks:
    - name: Check for f1 folder
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Create file f1 if directory f1 is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
